language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: GNFrsEx3fcghjSbXsAOkMHVxKZeqYxLRq5Wv8+ESUZc1qhNl2QwsjySDkxe4EH6211PYymuHGwpY1/wNZPukwnIsS8galJFAC6pu2e2IMJyWf2y9FsKtLkwPLCqmco+1Xdxm7x8Hih1KFGNZx5rZm9FdhyuRuRmYw1rU4pT1eODt4KxaK255kYT1xn3dAxAFGKPIULiUPZ7m+GCzL1d4yut0pqIRI8MTT8ovc04/lxByu5mJ81DH5t+AV4TCxp6CBOdbUZRF53dQRA99N+8XIVgeTms/B5jZwt7X2GnynVwg1nD1q9C1vOcEHhIjrxZ3oqcd9CZfbQxCq0/7Nvse/VRSR6FhvBwvsftUTsW8jnVJMDOuxqAlOA8a9jqgO5MQpTsxite1ghpBULLnW4TAAf8sZXE70gKOM5GLy2TEKNHuUMxiuAqV4fDLTX/FjHnoAFHoAXCFSmcZs3EXgTJ2JrLl+e7Whgi/YBJVnpfvA8KyJk3+kHRhhZNJlktxlapArMmyo+T0wJAAVkuD7UvR6hMJmeNOCvX4wj8ORI8RLZ4g+8jDVYafZ/Vry0RgrqWQz8TJFsNT4oiCYh0yQ/Jd9vZygUw3+vcCwig/AW4ENqtceVfvYQgLag+L12Jgsqp2RCAtMNB54H+flwv1v/U3GL4FbFI3qw+m8usoFhPvStI=
  app: aptifootball-api
  on:
    repo: aptitud/aptifootball
